import type { Metadata } from "next";
import { Space_Grotesk, Open_Sans, Text_Me_One, EB_Garamond } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300","400", "700"], 
  variable: "--font-space-grotesk",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300","400", "500", "600",  "700"],
  variable: "--font-open-sans",
});

const textMeOne = Text_Me_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-text-me-one",
});
const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["800","400", "500", "600",  "700"], 
  variable: "--font-eb-garamond",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${openSans.variable} ${textMeOne.variable} antialiased bg-primary text-white`}
      >
        {children}
      </body>
    </html>
  );
}